### ISSUE TITLE
Steams do not start

### ISSUE THREAD

**Issue by motionbug** [mrolix/plugin.video.neterratv#3]
Something has changed on Net terra's website as the streams do not start now...

**Comment by mrolix** [comment]
I updated neterratv.py. Please replace with the updated version.

**Comment by mrolix** [comment]
Please check comments under issue 
https://github.com/mrolix/plugin.video.neterratv/issues/4
I close this one.
Thanks Olaf

**Comment by mrolix** [comment]
Closed.

**Comment by motionbug** [comment]
thanks again! awesome
